export interface ChecklistItem {
  id: string;
  text: string;
  leakageImpact: number; // estimated percentage of leakage risk if failed
  tip: string;
}

export interface ProcessStage {
  number: number;
  title: string;
  controlArea: string;
  checklistItems: ChecklistItem[];
}

export interface ProcessLayers {
  flow: string;
  controls: string;
  risks: string[];
  kpis: string[];
  insights: string[];
}

export interface RetailProcess {
  id: number;
  name: string;
  domain: string;
  layers: ProcessLayers;
  stages: ProcessStage[];
}

export const processDomains = [
  { id: 'customer-sales', name: 'Customer & Sales Processes' },
  { id: 'inventory-ops', name: 'Inventory & Operations Processes' },
  { id: 'procurement-sc', name: 'Procurement & Supply Chain Processes' },
  { id: 'finance-compliance', name: 'Finance & Compliance Processes' },
  { id: 'human-capital', name: 'Human Capital Processes' },
  { id: 'executive-control', name: 'Executive Control Processes' }
];

export const retailProcesses: RetailProcess[] = [
  // 1. CRM & Lead Management
  {
    id: 1,
    name: 'CRM & Lead Management',
    domain: 'customer-sales',
    layers: {
      flow: 'Lead Capture → Qualification → Allocation → Follow-up → Quote Generation → Conversion Analysis',
      controls: 'Automated round-robin allocation, SLA limits on follow-ups, manager-approved discount codes',
      risks: ['Lead leakage to competitors', 'Follow-up delays costing conversions', 'Unauthorized pricing waivers by staff'],
      kpis: ['Lead Response Time (mins)', 'Conversion Rate %', 'Follow-up SLA Adherence %', 'Drop-off Rate %'],
      insights: ['Campaign Lead-to-Revenue Efficiency', 'Channel Quality Score', 'Lead Churn Heatmap']
    },
    stages: [
      {
        number: 1,
        title: 'Lead Ingestion & Profile Security',
        controlArea: 'Access controls and encryption on customer PII',
        checklistItems: [
          { id: 'g-1-1-1', text: 'Verify lead source tags are automatically generated by the CRM', leakageImpact: 0.2, tip: 'Prevents manual overwriting of marketing attribution data.' },
          { id: 'g-1-1-2', text: 'Ensure customer PII fields (phone, email) are masked in front-end views', leakageImpact: 0.3, tip: 'Reduces risk of staff exporting and stealing client databases.' }
        ]
      },
      {
        number: 2,
        title: 'Allocation & Action SLAs',
        controlArea: 'Automated allocation rules and callback timers',
        checklistItems: [
          { id: 'g-1-2-1', text: 'Confirm round-robin rules assign leads instantly to active showroom consultants', leakageImpact: 0.2, tip: 'Minimizes customer wait times and optimizes floor traffic.' },
          { id: 'g-1-2-2', text: 'Verify 24-hour SLA triggers send alert to floor managers for uncontacted leads', leakageImpact: 0.2, tip: 'Protects pipeline velocity and stops lead decay.' }
        ]
      },
      {
        number: 3,
        title: 'Conversion & Margin Safeguards',
        controlArea: 'Manager override logs and discount bounds',
        checklistItems: [
          { id: 'g-1-3-1', text: 'Enforce system blocks on customer-facing price estimates without manager OTP validation', leakageImpact: 0.4, tip: 'Prevents staff from offering unauthorized discounts below target margin.' }
        ]
      }
    ]
  },
  // 2. Customer Lifecycle Management
  {
    id: 2,
    name: 'Customer Lifecycle Management',
    domain: 'customer-sales',
    layers: {
      flow: 'Acquisition → First Purchase → Loyalty Enrolment → Tier Upgrades → Churn Prevention → Win-back',
      controls: 'Unique customer tokens, loyalty point ledger locks, churn probability alerts',
      risks: ['Loyalty point inflation fraud', 'VIP downgrade complaints', 'Inactive buyer accumulation'],
      kpis: ['Customer Lifetime Value (CLV)', 'Repurchase Rate %', 'Active Member Share %', 'Redemption Rate %'],
      insights: ['Churn Heatmap', 'Customer Retention Cohorts', 'Segment Value Velocity']
    },
    stages: [
      {
        number: 1,
        title: 'Onboarding & Unique Tokenization',
        controlArea: 'Verification of customer registry and profile uniqueness',
        checklistItems: [
          { id: 'g-2-1-1', text: 'Validate customer mobile number via OTP on profile creation', leakageImpact: 0.2, tip: 'Prevents creation of duplicate records and point manipulation.' },
          { id: 'g-2-1-2', text: 'Verify unique customer token (LID) matches across POS and CRM databases', leakageImpact: 0.1, tip: 'Ensures single source of truth for purchase tracking.' }
        ]
      },
      {
        number: 2,
        title: 'Loyalty & Reward Control',
        controlArea: 'Rules-based point accrual and verification logs',
        checklistItems: [
          { id: 'g-2-2-1', text: 'Ensure points accrued are calculated automatically based on product margins', leakageImpact: 0.3, tip: 'Prevents manual point padding by billing staff.' },
          { id: 'g-2-2-2', text: 'Audit point redemption requests to mandate customer OTP validation', leakageImpact: 0.3, tip: 'Stops internal staff from draining customer loyalty points.' }
        ]
      },
      {
        number: 3,
        title: 'Retention & Win-Back Triggers',
        controlArea: 'Automated inactive account warnings',
        checklistItems: [
          { id: 'g-2-3-1', text: 'Verify CRM flags high-value VIP customers approaching 180-day inactivity', leakageImpact: 0.2, tip: 'Triggers automated personal outreach before churn occurs.' }
        ]
      }
    ]
  },
  // 3. Sales-to-Cash
  {
    id: 3,
    name: 'Sales-to-Cash',
    domain: 'customer-sales',
    layers: {
      flow: 'Item Selection → Estimation → Billing → Payment Processing → Delivery → Day-end Settlement',
      controls: 'Barcode scan enforcement, POS-integrated UPI terminals, dual cash verification',
      risks: ['Cash drawer theft', 'Card transaction chargebacks', 'Bill modification post-delivery'],
      kpis: ['Daily Billing Discrepancy Rate %', 'Avg Checkout Time (mins)', 'Cash-to-Digital Payment Ratio'],
      insights: ['Revenue Integrity Score', 'Store Till Leakage Alerts', 'Billing Cycle Efficiencies']
    },
    stages: [
      {
        number: 1,
        title: 'Billing & Barcode Controls',
        controlArea: 'Ensuring all billing matches physical barcode scans',
        checklistItems: [
          { id: 'g-3-1-1', text: 'Enforce that all invoice items are scanned via barcode (no manual SKU override)', leakageImpact: 0.5, tip: 'Stops cashiers from billing premium diamond items under cheaper gold SKUs.' }
        ]
      },
      {
        number: 2,
        title: 'Payment Integration & Webhooks',
        controlArea: 'Automatic verification of payment gateways',
        checklistItems: [
          { id: 'g-3-2-1', text: 'Verify UPI and card terminal payment webhooks link directly to the invoice ID', leakageImpact: 0.4, tip: 'Eliminates cashier entry errors and manual payment fraud.' },
          { id: 'g-3-2-2', text: 'Confirm system blocks bill printing until payment confirmation is received', leakageImpact: 0.3, tip: 'Prevents customer exit with unpaid items.' }
        ]
      },
      {
        number: 3,
        title: 'Till Reconciliation & Balancing',
        controlArea: 'Day-end cash drawer balancing audits',
        checklistItems: [
          { id: 'g-3-3-1', text: 'Audit cash till balances against system invoice records at day-close', leakageImpact: 0.2, tip: 'Detects petty cash leaks and till shortages immediately.' }
        ]
      }
    ]
  },
  // 4. Customer Returns
  {
    id: 4,
    name: 'Customer Returns',
    domain: 'customer-sales',
    layers: {
      flow: 'Return Request → Purity Testing → Weight Verification → original Invoice Verification → Credit Note Generation',
      controls: 'Karatometer assay check, invoice ID validation, manager approval for value credit',
      risks: ['Accepting counterfeit jewellery', 'Refunding incorrect invoice amounts', 'Unauthorized store credits'],
      kpis: ['Return Rate %', 'Purity Variance %', 'Processing Time (mins)', 'Manager Exceptions %'],
      insights: ['Product Quality Issues Heatmap', 'Return Leakage Score', 'Fraud Risk Flagging']
    },
    stages: [
      {
        number: 1,
        title: 'Authentication & Invoice Match',
        controlArea: 'Verification of sale legitimacy',
        checklistItems: [
          { id: 'g-4-1-1', text: 'Mandate original invoice scan and system match prior to return intake', leakageImpact: 0.3, tip: 'Stops fraud loops involving returned stolen stock.' }
        ]
      },
      {
        number: 2,
        title: 'Purity & Weight Verification',
        controlArea: 'Assay and metal integrity testing',
        checklistItems: [
          { id: 'g-4-2-1', text: 'Verify returned items undergo mandatory Karatometer purity assay', leakageImpact: 0.5, tip: 'Protects inventory from gold-plated copper counterfeits.' },
          { id: 'g-4-2-2', text: 'Compare return weight against original invoice weight down to 0.01g', leakageImpact: 0.4, tip: 'Detects stone switching or minor metal shaving.' }
        ]
      },
      {
        number: 3,
        title: 'Settlement & Vault Intake',
        controlArea: 'Credit note controls and separation of stock',
        checklistItems: [
          { id: 'g-4-3-1', text: 'Audit credit note issuance records to require manager co-sign in ERP', leakageImpact: 0.3, tip: 'Prevents staff from creating ghost return store credits.' }
        ]
      }
    ]
  },
  // 5. Exchange & Buyback
  {
    id: 5,
    name: 'Exchange & Buyback',
    domain: 'customer-sales',
    layers: {
      flow: 'Verification → Assay testing → Value estimation → Deductions → Consent → Exchange Voucher',
      controls: 'Daily buyback rate locks, standard deduction charts, scrap melting approvals',
      risks: ['Overvaluation of customer gold', 'Incorrect deduction percentages', 'Melting weight losses'],
      kpis: ['Buyback Volume (g)', 'Deduction Leakage %', 'Valuation Discrepancy %', 'Meltdown Loss %'],
      insights: ['Branch Exchange Margins', 'Buyback Valuation Variance', 'Exchange Risk Indicator']
    },
    stages: [
      {
        number: 1,
        title: 'Authentication & Intake Weight',
        controlArea: 'Establishing baseline weights under dual custody',
        checklistItems: [
          { id: 'g-5-1-1', text: 'Calibrate scales using government certified weights before exchange', leakageImpact: 0.3, tip: 'Ensures measurement accuracy and legal compliance.' }
        ]
      },
      {
        number: 2,
        title: 'Purity Deductions Calibration',
        controlArea: 'Consistent deduction rate engine application',
        checklistItems: [
          { id: 'g-5-2-1', text: 'Lock deduction percentages in system based on assay karat readings', leakageImpact: 0.4, tip: 'Stops operators from reducing deductions to favor individuals.' },
          { id: 'g-5-2-2', text: 'Confirm live MCX buyback rates cannot be overridden manually', leakageImpact: 0.4, tip: 'Protects floor margins against rate variance losses.' }
        ]
      },
      {
        number: 3,
        title: 'Melt Segregation & Reconciliation',
        controlArea: 'Control of buyback scrap prior to refining',
        checklistItems: [
          { id: 'g-5-3-1', text: 'Verify exchange items are moved directly to scrap vault (no mixing with showroom inventory)', leakageImpact: 0.3, tip: 'Prevents resale of unrefined customer scrap.' }
        ]
      }
    ]
  },
  // 6. Old Gold Procurement & Exchange
  {
    id: 6,
    name: 'Old Gold Procurement & Exchange',
    domain: 'customer-sales',
    layers: {
      flow: 'Customer Intake → Weighment → Purity Testing → Valuation → Consent → Storage → Melting → Reconciliation → Inventory Creation',
      controls: '200+ Control Checkpoints',
      risks: ['Fraud Risks', 'Weight Risks', 'Purity Risks', 'Custody Risks', 'Compliance Risks'],
      kpis: ['Processing Time', 'Loss %', 'Variance %', 'Recovery %', 'Exception Rate'],
      insights: ['Branch Risk Score', 'Employee Risk Score', 'Fraud Exposure Score']
    },
    stages: [
      {
        number: 1,
        title: 'Intake & Testing',
        controlArea: 'Weight & Purity Audit',
        checklistItems: [
          { id: 'g-6-1-1', text: 'Verify scale calibrations daily against certified weights', leakageImpact: 0.3, tip: 'Ensures absolute intake weight accuracy.' },
          { id: 'g-6-1-2', text: 'Log Karatometer verification values directly to customer profile', leakageImpact: 0.4, tip: 'Prevents manual entry of inaccurate gold purity.' },
          { id: 'g-6-1-3', text: 'Record customer ID and verify KYC compliance for transactions above regulatory limits', leakageImpact: 0.2, tip: 'Avoids anti-money laundering compliance fines.' }
        ]
      },
      {
        number: 2,
        title: 'Melting & Refining',
        controlArea: 'Weight Verification',
        checklistItems: [
          { id: 'g-6-2-1', text: 'Compare melt weight against intake weight to check variance', leakageImpact: 0.4, tip: 'Detects unauthorized gold retention during melting.' },
          { id: 'g-6-2-2', text: 'Inspect melt crucible and recovery filters post-melt', leakageImpact: 0.2, tip: 'Ensures zero gold recovery loss in Crucible slag.' }
        ]
      },
      {
        number: 3,
        title: 'Valuation & Settlement',
        controlArea: 'Treasury Rates Integration',
        checklistItems: [
          { id: 'g-6-3-1', text: 'Verify deductions match locked system karat grids', leakageImpact: 0.3, tip: 'Stops staff from applying incorrect deduction rates.' },
          { id: 'g-6-3-2', text: 'Record customer signature consent on final valuation statement in ERP', leakageImpact: 0.1, tip: 'Secures legal record of client agreement.' }
        ]
      }
    ]
  },
  // 7. Gold Savings Scheme Management
  {
    id: 7,
    name: 'Gold Savings Scheme Management',
    domain: 'customer-sales',
    layers: {
      flow: 'Scheme Enrolment → Monthly Deposit → Rate Lock → Gram Credit Accrual → Redemption → Billing Match',
      controls: 'Strict monthly deposit validation, gram credit auto-locking, deposit date MCX snap',
      risks: ['Delayed deposit rate fraud', 'Accrual parameter tampering', 'Double redemption of schemes'],
      kpis: ['Scheme Customer Retention %', 'Redemption Velocity %', 'Gram Liability Exposure (g)', 'Default Rate %'],
      insights: ['Scheme Gram Liability Mismatch', 'Scheme Customer CLV Lift', 'Future Redemption Heatmap']
    },
    stages: [
      {
        number: 1,
        title: 'Enrolment & Mandate Setup',
        controlArea: 'Verification of scheme registration rules',
        checklistItems: [
          { id: 'g-7-1-1', text: 'Ensure saving scheme parameters (tenure, discount) are locked in system master', leakageImpact: 0.3, tip: 'Prevents staff from creating unauthorized custom schemes.' }
        ]
      },
      {
        number: 2,
        title: 'Deposit Logging & Gram Locking',
        controlArea: 'Automated gold rate conversion at deposit time',
        checklistItems: [
          { id: 'g-7-2-1', text: 'Enforce that gold grams credited are locked automatically using live MCX gold rate at payment time', leakageImpact: 0.5, tip: 'Stops cashier backdating deposits to peak-low rate days.' },
          { id: 'g-7-2-2', text: 'Verify deposit invoices generate automated customer WhatsApp receipt within 5 minutes', leakageImpact: 0.1, tip: 'Provides transparent confirmation to customers.' }
        ]
      },
      {
        number: 3,
        title: 'Redemption & Billing Match',
        controlArea: 'Scheme closure audits and voucher verification',
        checklistItems: [
          { id: 'g-7-3-1', text: 'Enforce dual verification (OTP + Manager Sign) in ERP to close and redeem scheme grams', leakageImpact: 0.4, tip: 'Stops staff from redeeming client savings without customer presence.' }
        ]
      }
    ]
  },
  // 8. Customer Service & Repair Management
  {
    id: 8,
    name: 'Customer Service & Repair Management',
    domain: 'customer-sales',
    layers: {
      flow: 'Intake Inspection → Weight Log → Job Card Issue → Workshop Dispatch → Repair Action → Quality Check → Customer Handover',
      controls: 'Initial photograph logs, precise weighing to 0.001g, workshop custody tracking, QC verification',
      risks: ['Metal shaving during repair', 'Replacing natural diamonds with synthetics', 'Custody loss in transit'],
      kpis: ['Service Turnaround Time (days)', 'Weight Variance %', 'Customer Quality Rating', 'Rework Rate %'],
      insights: ['Repair Value Contributions', 'Workshop Leakage Score', 'Client Satisfaction Index']
    },
    stages: [
      {
        number: 1,
        title: 'Intake Assessment & Weight Lock',
        controlArea: 'Securing intake weight and attributes',
        checklistItems: [
          { id: 'g-8-1-1', text: 'Record item weight to 0.001g and take high-resolution intake photos', leakageImpact: 0.4, tip: 'Protects store from client claims of pre-existing damage or weight loss.' },
          { id: 'g-8-1-2', text: 'Generate job card with detailed stone layout mapping in ERP', leakageImpact: 0.3, tip: 'Ensures diamond locations and counts are logged.' }
        ]
      },
      {
        number: 2,
        title: 'Workshop Custody & Job Work',
        controlArea: 'Securing transit and custody logs',
        checklistItems: [
          { id: 'g-8-2-1', text: 'Mandate digital warehouse sign-off when dispatched to job workshop', leakageImpact: 0.3, tip: 'Prevents inventory tracking losses during transit.' }
        ]
      },
      {
        number: 3,
        title: 'QC & Customer Handover',
        controlArea: 'Reconciliation of returned repair item',
        checklistItems: [
          { id: 'g-8-3-1', text: 'Compare post-repair weight against intake weight and log variance', leakageImpact: 0.4, tip: 'Detects unauthorized gold weight erosion during polishing/repairs.' }
        ]
      }
    ]
  },

  // INVENTORY & OPERATIONS (9-16)
  // 9. Raw Material Management
  {
    id: 9,
    name: 'Raw Material Management',
    domain: 'inventory-ops',
    layers: {
      flow: 'Purchase Receipt → Vault Storage → Melting Room Allocation → Issue to Production → Scrap Recovery → Vault Update',
      controls: 'Dual-custody vault access, daily weight balance reconciliation, scrap loss tracking',
      risks: ['Vault pilferage', 'Melting loss inflation', 'Unrecorded scrap theft'],
      kpis: ['Vault Weight Variance (g)', 'Melting Room Recovery Rate %', 'Vault Turn Velocity'],
      insights: ['Metal Inventory Value Risk', 'Raw Material Shrinkage Trends', 'Vault Custodian Performance']
    },
    stages: [
      {
        number: 1,
        title: 'Intake and Weight Validation',
        controlArea: 'Receiving verification of gold bars and loose gems',
        checklistItems: [
          { id: 'g-9-1-1', text: 'Weigh raw gold bars under dual-witness camera coverage upon delivery', leakageImpact: 0.4, tip: 'Ensures supplier weight matches invoice quantity.' }
        ]
      },
      {
        number: 2,
        title: 'Vault Custody Control',
        controlArea: 'Access logs and weight ledger integration',
        checklistItems: [
          { id: 'g-9-2-1', text: 'Mandate dual-pin electronic lock logs for every vault access', leakageImpact: 0.3, tip: 'Stops single operator access to high-value bullion.' },
          { id: 'g-9-2-2', text: 'Verify daily book weight matches physical vault audit counts', leakageImpact: 0.5, tip: 'Identifies raw material shrinkage immediately.' }
        ]
      },
      {
        number: 3,
        title: 'Production Issuance',
        controlArea: 'Tracking issues to manufacturing job cards',
        checklistItems: [
          { id: 'g-9-3-1', text: 'Lock metal issue logs directly to approved active manufacturing orders', leakageImpact: 0.4, tip: 'Prevents off-book metal issues to jewellers.' }
        ]
      }
    ]
  },
  // 10. Finished Goods Management
  {
    id: 10,
    name: 'Finished Goods Management',
    domain: 'inventory-ops',
    layers: {
      flow: 'QC Approval → HUID Tagging → Barcode Creation → Tray Assignment → Showroom Display → Billing Move',
      controls: 'Automatic HUID tag check, RFID tray scan matching, real-time stock status sync',
      risks: ['Display tray tag switching', 'HUID registry mismatches', 'Missing items from active displays'],
      kpis: ['RFID Scan Match Rate %', 'Display Loss Rate %', 'HUID Compliance Rate %'],
      insights: ['Display Tray Turnover Metrics', 'Stock Valuation by Karat', 'Tray Loss Heatmap']
    },
    stages: [
      {
        number: 1,
        title: 'Tagging & Compliance',
        controlArea: 'Applying security and legal compliance tags',
        checklistItems: [
          { id: 'g-10-1-1', text: 'Confirm BIS HUID database registry matching prior to barcode release', leakageImpact: 0.3, tip: 'Avoids regulatory fines for selling untraced gold.' }
        ]
      },
      {
        number: 2,
        title: 'Showroom Allocation & RFID Sync',
        controlArea: 'Display tray security mapping',
        checklistItems: [
          { id: 'g-10-2-1', text: 'Verify all display trays are scanned using RFID sensors at shift start and end', leakageImpact: 0.5, tip: 'Identifies missing display stock within minutes rather than weeks.' },
          { id: 'g-10-2-2', text: 'Audit tray allocations to block placement of high-value stock in low-security zones', leakageImpact: 0.2, tip: 'Optimizes store security layouts.' }
        ]
      },
      {
        number: 3,
        title: 'Sales Status Transition',
        controlArea: 'POS stock depletion triggers',
        checklistItems: [
          { id: 'g-10-3-1', text: 'Verify POS bill printing automatically flags barcode status as "Sold" in ERP', leakageImpact: 0.4, tip: 'Stops repeat scans of already sold item barcodes.' }
        ]
      }
    ]
  },
  // 11. Branch Inventory Transfers
  {
    id: 11,
    name: 'Branch Inventory Transfers',
    domain: 'inventory-ops',
    layers: {
      flow: 'Dispatch Request → Stock Selection → Weight Lock & Seal → Transit Security Log → Destination Receiving → Weight Re-check → Status Update',
      controls: 'Tamper-proof bag sealing, transit weight locks, destination weight match checks',
      risks: ['Transit theft by logistics', 'Weight shrinkage in transit', 'Receiving delays mask missing stock'],
      kpis: ['Transit Cycle Time (hours)', 'Weight Variance %', 'Tamper Seal Exception Rate', 'Discrepancy Resolution Time (mins)'],
      insights: ['Logistics Route Risk Score', 'Branch Receipt Delay Matrix', 'Transit Loss Exposure']
    },
    stages: [
      {
        number: 1,
        title: 'Dispatch & Seal',
        controlArea: 'Sealing and dispatch logging controls',
        checklistItems: [
          { id: 'g-11-1-1', text: 'Enforce use of serialized tamper-proof bags for all inter-store transfers', leakageImpact: 0.4, tip: 'Ensures visual identification of transit tampering.' },
          { id: 'g-11-1-2', text: 'Record bag weight to 0.01g and seal ID in dispatch manifest', leakageImpact: 0.3, tip: 'Locks sending weights in database.' }
        ]
      },
      {
        number: 2,
        title: 'Transit Verification',
        controlArea: 'Logistics tracking and security logs',
        checklistItems: [
          { id: 'g-11-2-1', text: 'Verify transit bags are scanned at security checkpoints', leakageImpact: 0.2, tip: 'Ensures custody tracking throughout transit.' }
        ]
      },
      {
        number: 3,
        title: 'Receiving & Purity Audit',
        controlArea: 'Inward verification at destination branch',
        checklistItems: [
          { id: 'g-11-3-1', text: 'Require destination showroom to weigh bags before breaking seals', leakageImpact: 0.5, tip: 'Detects bag tampering and weight differences instantly.' }
        ]
      }
    ]
  },
  // 12. Inventory Audits & Stock Counts
  {
    id: 12,
    name: 'Inventory Audits & Stock Counts',
    domain: 'inventory-ops',
    layers: {
      flow: 'Schedule Generation → RFID/Barcode Scanning → Discrepancy Flagging → Reconciliation Audits → Log Update',
      controls: 'Surprise count schedules, independent auditor oversight, system-locked count balances',
      risks: ['Ghost stock masking thefts', 'Auditor collusion with staff', 'Stale ledger data'],
      kpis: ['Stock Accuracy %', 'Audit Discrepancy Rate %', 'Count Time (hours)', 'Unexplained Variances (g)'],
      insights: ['Showroom Shrinkage Heatmap', 'Audit Compliance Rating', 'Loss Exposure Score']
    },
    stages: [
      {
        number: 1,
        title: 'Audit Scheduling & Prep',
        controlArea: 'Independent audit trigger governance',
        checklistItems: [
          { id: 'g-12-1-1', text: 'Confirm stock count schedules are generated automatically by HO without branch warning', leakageImpact: 0.3, tip: 'Prevents showrooms from temporarily hiding stock shortages.' }
        ]
      },
      {
        number: 2,
        title: 'Scanning & Discrepancy Log',
        controlArea: 'System-locked physical scans tracking',
        checklistItems: [
          { id: 'g-12-2-1', text: 'Lock ERP ledger balance adjustments during physical counting cycles', leakageImpact: 0.4, tip: 'Stops staff from modifying system records during counts.' },
          { id: 'g-12-2-2', text: 'Audit discrepancies to require independent HO administrator overrides', leakageImpact: 0.5, tip: 'Prevents manager collusion in writing off missing gold.' }
        ]
      },
      {
        number: 3,
        title: 'Reconciliation',
        controlArea: 'Final audit report balancing',
        checklistItems: [
          { id: 'g-12-3-1', text: 'Verify uncounted barcodes are automatically deactivated and flagged for investigation', leakageImpact: 0.4, tip: 'Stops billing of missing or stolen inventory.' }
        ]
      }
    ]
  },
  // 13. Manufacturing & Job Work
  {
    id: 13,
    name: 'Manufacturing & Job Work',
    domain: 'inventory-ops',
    layers: {
      flow: 'Design Approval → Alloy & Gold Allocation → Jeweller Allocation → Manufacturing → Quality Assay → Scrap Recovery → Delivery',
      controls: 'Jeweller gold balance ledgers, alloy purity standards, recovery dust collection',
      risks: ['Excessive gold dust loss', 'Alloy quality diluting purity', 'Substitution of loose gems'],
      kpis: ['Dust Loss % (tolerance < 0.5%)', 'Purity Test Pass Rate %', 'Production Lead Time (days)'],
      insights: ['Jeweller Performance Scores', 'Alloy Purity Compliance Matrix', 'Manufacturing Cost Dynamics']
    },
    stages: [
      {
        number: 1,
        title: 'Design Allocation & Gold Issue',
        controlArea: 'Weighment controls during jeweller issue',
        checklistItems: [
          { id: 'g-13-1-1', text: 'Log precise weight and karat of metal issued to jeweller job cards', leakageImpact: 0.4, tip: 'Prevents excess bullion release beyond design limit.' }
        ]
      },
      {
        number: 2,
        title: 'Manufacturing & Dust Auditing',
        controlArea: 'Gold dust recovery and workshop loss parameters',
        checklistItems: [
          { id: 'g-13-2-1', text: 'Audit jeweller sweepings and recovery files monthly against issue balances', leakageImpact: 0.3, tip: 'Detects systematic gold shaving in workshop.' },
          { id: 'g-13-2-2', text: 'Lock gold loss calculations to industry standards based on complexity', leakageImpact: 0.3, tip: 'Prevents excessive loss write-offs by manufacturers.' }
        ]
      },
      {
        number: 3,
        title: 'Assay Receipt',
        controlArea: 'Purity validation of finished item',
        checklistItems: [
          { id: 'g-13-3-1', text: 'Enforce automated Karatometer check on every manufactured item before vault entry', leakageImpact: 0.5, tip: 'Stops accepting low-karat items from manufacturers.' }
        ]
      }
    ]
  },
  // 14. Packing Material Management
  {
    id: 14,
    name: 'Packing Material Management',
    domain: 'inventory-ops',
    layers: {
      flow: 'Order Placement → Warehouse Inward → Box Inventory Count → Issue to Billing Tills → Customer Billing Match',
      controls: 'Packing items SKU codes, till allocation logs, billing box reconciliation',
      risks: ['Box inventory theft (high-cost boxes)', 'Incorrect till allocation', 'Stockout of premium packaging'],
      kpis: ['Packaging Cost % of Sales', 'Till Box Reconciliation Variance %', 'Packaging Stock Accuracy %'],
      insights: ['Packaging Margin Impact', 'Till Packaging Usage Efficiency', 'Packaging Value Velocity']
    },
    stages: [
      {
        number: 1,
        title: 'Procurement & Tagging',
        controlArea: 'Assigning SKU codes to premium boxes',
        checklistItems: [
          { id: 'g-14-1-1', text: 'Confirm premium leather boxes are assigned unique SKU codes in ERP', leakageImpact: 0.1, tip: 'Enables precise unit-level inventory tracking.' }
        ]
      },
      {
        number: 2,
        title: 'Till Allocation',
        controlArea: 'Controlling stock levels at registers',
        checklistItems: [
          { id: 'g-14-2-1', text: 'Verify box allocations to showroom registers are logged in ERP', leakageImpact: 0.2, tip: 'Identifies till-level packaging losses.' }
        ]
      },
      {
        number: 3,
        title: 'Sales Matching',
        controlArea: 'Automatic package count deductions',
        checklistItems: [
          { id: 'g-14-3-1', text: 'Enforce system-driven deductions of boxes on invoice printing', leakageImpact: 0.2, tip: 'Matches packaging usage to transaction counts.' }
        ]
      }
    ]
  },
  // 15. Repair Inventory Tracking
  {
    id: 15,
    name: 'Repair Inventory Tracking',
    domain: 'inventory-ops',
    layers: {
      flow: 'Receipt → Location Tagging → Workshop Transfer → Part Replacement → QC → Handover',
      controls: 'Repair bag tracking codes, part replacement approval logs, dual custody vault logs',
      risks: ['Replacing customer gems', 'Loss of item in workshop', 'Unauthorized repair charges'],
      kpis: ['Repair Cycle Time (days)', 'Parts Variance Rate %', 'QC Approval Rate %'],
      insights: ['Workshop Quality Index', 'Repair Loss Heatmap', 'Staff Productivity Scores']
    },
    stages: [
      {
        number: 1,
        title: 'Repair Inward Logging',
        controlArea: 'Securing item details',
        checklistItems: [
          { id: 'g-15-1-1', text: 'Confirm all repair items receive unique tracked repair tags', leakageImpact: 0.3, tip: 'Prevents mix-ups of customer jewellery.' }
        ]
      },
      {
        number: 2,
        title: 'Part Replacements',
        controlArea: 'Logging material changes',
        checklistItems: [
          { id: 'g-15-2-1', text: 'Ensure replacement parts (e.g., locks, settings) are scanned from active ERP inventory', leakageImpact: 0.2, tip: 'Reconciles parts usage and cost calculations.' }
        ]
      },
      {
        number: 3,
        title: 'Verification & Handover',
        controlArea: 'Customer validation checklist',
        checklistItems: [
          { id: 'g-15-3-1', text: 'Validate customer signature and OTP validation at handover', leakageImpact: 0.2, tip: 'Eliminates false claims of non-delivery.' }
        ]
      }
    ]
  },
  // 16. Scrap & Recovery Management
  {
    id: 16,
    name: 'Scrap & Recovery Management',
    domain: 'inventory-ops',
    layers: {
      flow: 'Floor Collection → Weight Log → Melting Vault Intake → Chemical Recovery Assay → Gold Recovery Log → Reconciliation',
      controls: 'Locked chemical recovery bins, weight logs, assay comparison matrix',
      risks: ['Chemical recovery theft', 'Floor sweepings gold theft', 'Incorrect recovery calculations'],
      kpis: ['Recovery Gold Volume (g)', 'Assay Match Accuracy %', 'Floor Sweeping Volume Variance %'],
      insights: ['Recovery Value Impact', 'Showroom Gold Dust Recovery Matrix', 'Operator Performance Scores']
    },
    stages: [
      {
        number: 1,
        title: 'Collection & Vaulting',
        controlArea: 'Floor sweeping containment',
        checklistItems: [
          { id: 'g-16-1-1', text: 'Ensure chemical recovery tanks are sealed and monitored via cameras', leakageImpact: 0.3, tip: 'Stops unauthorized scrap gold extraction.' }
        ]
      },
      {
        number: 2,
        title: 'Chemical Refining Audit',
        controlArea: 'Comparing expected vs actual recovery weights',
        checklistItems: [
          { id: 'g-16-2-1', text: 'Verify recovery weights match chemical assay projections', leakageImpact: 0.4, tip: 'Detects diversion of refined gold dust.' }
        ]
      },
      {
        number: 3,
        title: 'Reconciliation',
        controlArea: 'Accounting and ledger updates',
        checklistItems: [
          { id: 'g-16-3-1', text: 'Ensure recovered gold is credited to raw material inventory in ERP', leakageImpact: 0.3, tip: 'Completes the recovery-to-vault accounting cycle.' }
        ]
      }
    ]
  },

  // PROCUREMENT & SUPPLY CHAIN (17-21)
  // 17. Procure-to-Pay
  {
    id: 17,
    name: 'Procure-to-Pay',
    domain: 'procurement-sc',
    layers: {
      flow: 'Requisition → PO Release → GRN Creation → Invoice Verification → 3-Way Match → Payment Execution',
      controls: 'Automated 3-way matching, MCX live price PO locks, payment hold rules',
      risks: ['Paying incorrect invoice prices', 'Supplier invoice padding', 'Overpaying on metal rates'],
      kpis: ['P2P Cycle Time (days)', 'Invoice Error Rate %', 'Match Accuracy Rate %'],
      insights: ['Spend Analysis by Supplier', 'Rate Lock Margins Saved', 'Payment Batch Volumes']
    },
    stages: [
      {
        number: 1,
        title: 'PO Creation & MCX Locking',
        controlArea: 'Ensuring metal rate protection',
        checklistItems: [
          { id: 'g-17-1-1', text: 'Verify PO gold rates are locked using the live MCX gold index', leakageImpact: 0.4, tip: 'Stops supplier price inflation on market spikes.' }
        ]
      },
      {
        number: 2,
        title: 'GRN Receiving & Match Check',
        controlArea: 'Three-way check on received items',
        checklistItems: [
          { id: 'g-17-2-1', text: 'Enforce ERP 3-way matching (PO rate ↔ GRN weight ↔ Invoice amount)', leakageImpact: 0.5, tip: 'Blocks payouts on invoice-PO weight discrepancies.' }
        ]
      },
      {
        number: 3,
        title: 'Payment Approval',
        controlArea: 'GSTR-2B validation before settlement',
        checklistItems: [
          { id: 'g-17-3-1', text: 'Verify supplier payments are released only after GSTR-2B tax compliance matching', leakageImpact: 0.3, tip: 'Prevents cash losses on supplier tax defaults.' }
        ]
      }
    ]
  },
  // 18. Vendor Management
  {
    id: 18,
    name: 'Vendor Management',
    domain: 'procurement-sc',
    layers: {
      flow: 'Vendor Application → KYC Check → Purity Cert. Check → Margin Lock → Master Creation → Portal Access',
      controls: 'Supplier master approval matrix, mandatory bank detail match checks, trade agreement logs',
      risks: ['Collusion with fake vendors', 'Tampering with payment bank data', 'Unauthorized margin agreements'],
      kpis: ['Vendor Onboarding Time (days)', 'KYC Compliance Rate %', 'Supplier Master Change Rate %'],
      insights: ['Vendor Concentration Risk', 'Supplier Margin Comparisons', 'Vendor Compliance Index']
    },
    stages: [
      {
        number: 1,
        title: 'Onboarding & KYC Validation',
        controlArea: 'Supplier registration controls',
        checklistItems: [
          { id: 'g-18-1-1', text: 'Confirm supplier GSTIN and bank details match master documents', leakageImpact: 0.3, tip: 'Stops payments going to false or redirected accounts.' }
        ]
      },
      {
        number: 2,
        title: 'Purity & Wastage Rules Lock',
        controlArea: 'Trade contract system locks',
        checklistItems: [
          { id: 'g-18-2-1', text: 'Lock vendor wastage and making charge rules directly in ERP supplier profiles', leakageImpact: 0.4, tip: 'Prevents staff from bypassing agreed supplier charge bounds.' }
        ]
      },
      {
        number: 3,
        title: 'Master Auditing',
        controlArea: 'Supplier detail modification reviews',
        checklistItems: [
          { id: 'g-18-3-1', text: 'Audit supplier master edit logs to require independent HO signs', leakageImpact: 0.3, tip: 'Tracks and regulates changes to supplier files.' }
        ]
      }
    ]
  },
  // 19. Supplier Performance Management
  {
    id: 19,
    name: 'Supplier Performance Management',
    domain: 'procurement-sc',
    layers: {
      flow: 'Delivery Analysis → Purity Audit Check → Weight Loss Check → Scorecard Issue → Review meeting → Allocation adjustment',
      controls: 'System scorecards, purity failure thresholds, lead time metrics',
      risks: ['Accepting systematically lower purity gold', 'Ignoring persistent delivery delays', 'Over-dependence on underperforming vendors'],
      kpis: ['Purity Failure Rate %', 'SLA Delivery Adherence %', 'Avg Delivery Lead Time (days)'],
      insights: ['Supplier Scorecard Rankings', 'Procurement Performance Matrix', 'Vendor SLA Risk Map']
    },
    stages: [
      {
        number: 1,
        title: 'QC Auditing',
        controlArea: 'Documenting supplier quality rates',
        checklistItems: [
          { id: 'g-19-1-1', text: 'Confirm supplier purity tests are logged systematically per delivery', leakageImpact: 0.4, tip: 'Tracks historical supplier quality levels.' }
        ]
      },
      {
        number: 2,
        title: 'SLA Tracking',
        controlArea: 'Lead time calculations',
        checklistItems: [
          { id: 'g-19-2-1', text: 'Verify actual delivery dates are matched automatically to PO timelines in ERP', leakageImpact: 0.2, tip: 'Calculates true supplier lead times.' }
        ]
      },
      {
        number: 3,
        title: 'Allocation Adjustments',
        controlArea: 'Purity failure response governance',
        checklistItems: [
          { id: 'g-19-3-1', text: 'Confirm system flags and blocks orders to vendors with >1% purity fail rates', leakageImpact: 0.4, tip: 'Enforces quality compliance blocks.' }
        ]
      }
    ]
  },
  // 20. Logistics & Transportation
  {
    id: 20,
    name: 'Logistics & Transportation',
    domain: 'procurement-sc',
    layers: {
      flow: 'Dispatch Approval → Transit route configuration → Armed Escort Alloc. (as required) → Shipping scan → Tracking → Safe Inward Scan',
      controls: 'GPS transit tracking, armed escort manifests, verified transit locks',
      risks: ['Highway robbery of high-value gold', 'Driver diversion', 'Logistics scan failures'],
      kpis: ['Logistics SLA Compliance %', 'Transit Route Deviations', 'Delivery Window Variance %'],
      insights: ['Transit Route Safety Index', 'Logistics Partner Costs comparison', 'Armed Escort Coverage Efficiency']
    },
    stages: [
      {
        number: 1,
        title: 'Dispatch & Escort Allocation',
        controlArea: 'Securing shipment values',
        checklistItems: [
          { id: 'g-20-1-1', text: 'Verify armed escort allocations are signed off for shipments exceeding limit value', leakageImpact: 0.4, tip: 'Ensures security and insurance compliance for high-value logistics.' }
        ]
      },
      {
        number: 2,
        title: 'GPS Tracking Integration',
        controlArea: 'Active transit tracking',
        checklistItems: [
          { id: 'g-20-2-1', text: 'Confirm transit route GPS geofencing alerts are active', leakageImpact: 0.3, tip: 'Sends immediate warning if shipment diverges from planned paths.' }
        ]
      },
      {
        number: 3,
        title: 'Receiving Scan',
        controlArea: 'Arrival verification',
        checklistItems: [
          { id: 'g-20-3-1', text: 'Log package physical check and box status scanning at arrival', leakageImpact: 0.3, tip: 'Ensures transit custody closure.' }
        ]
      }
    ]
  },
  // 21. Goods Receipt & Inspection
  {
    id: 21,
    name: 'Goods Receipt & Inspection',
    domain: 'procurement-sc',
    layers: {
      flow: 'Shipment Intake → Weighment → Karatometer Scan → Stone Setting Audit → Barcode/Tag Issue → Vault Dispatch',
      controls: 'Direct weight scale digital logging, purity verification check, RFID tag audit',
      risks: ['Accepting low-purity consignments', 'Incorrect weight records', 'Billing untracked stones'],
      kpis: ['Inward Inspection Pass Rate %', 'Avg Receipt Time (mins)', 'Weight Variance %'],
      insights: ['Supplier Quality Performance Score', 'Showroom Intake Volumes', 'Tagging Cycle Times']
    },
    stages: [
      {
        number: 1,
        title: 'Intake Weighment',
        controlArea: 'Direct scale ledger integration',
        checklistItems: [
          { id: 'g-21-1-1', text: 'Enforce digital scale weight capture directly into ERP (no manual keyboard typing)', leakageImpact: 0.4, tip: 'Stops staff from manually adjusting intake gold weights.' }
        ]
      },
      {
        number: 2,
        title: 'Purity & Setting Audit',
        controlArea: 'Refining quality verify logs',
        checklistItems: [
          { id: 'g-21-2-1', text: 'Verify every received jewellery item is scanned using Karatometers', leakageImpact: 0.5, tip: 'Blocks intake of gold with hidden solder weight or low purity.' }
        ]
      },
      {
        number: 3,
        title: 'Tagging & Release',
        controlArea: 'Compliance tag verification',
        checklistItems: [
          { id: 'g-21-3-1', text: 'Confirm BIS HUID validation is complete before issuing barcode tags', leakageImpact: 0.3, tip: 'Ensures legal compliance before inventory release.' }
        ]
      }
    ]
  },

  // FINANCE & COMPLIANCE (22-27)
  // 22. Cash Management
  {
    id: 22,
    name: 'Cash Management',
    domain: 'finance-compliance',
    layers: {
      flow: 'Cash Billing → Till Storage → Vault Drop → Bank Deposit Dispatch → Bank Receipt Match',
      controls: 'Vault dual-custody access, deposit carrier logs, bank balance auto-matching',
      risks: ['Store till embezzlement', 'Armed carrier robbery', 'Unrecorded cash drawer discrepancies'],
      kpis: ['Cash Till Discrepancy %', 'Days to Bank Deposit', 'Bank Statement Match Rate %'],
      insights: ['Store Cash Flow Volumes', 'Cash-to-Bank Cycle times', 'Till Security Exposure']
    },
    stages: [
      {
        number: 1,
        title: 'Till Balancing',
        controlArea: 'POS cash drawer reconciliation audits',
        checklistItems: [
          { id: 'g-22-1-1', text: 'Conduct physical cash drawer audits at shift handovers', leakageImpact: 0.3, tip: 'Detects short-tills and till manipulations immediately.' }
        ]
      },
      {
        number: 2,
        title: 'Vault Drops',
        controlArea: 'Dual key vault drops tracking',
        checklistItems: [
          { id: 'g-22-2-1', text: 'Verify till cash drops exceeding limit are moved immediately to dual-key vaults', leakageImpact: 0.4, tip: 'Reduces till cash exposure during floor hours.' }
        ]
      },
      {
        number: 3,
        title: 'Bank Deposits',
        controlArea: 'Transit security dispatch checks',
        checklistItems: [
          { id: 'g-22-3-1', text: 'Ensure cash bank deposits match system transit slips before dispatch', leakageImpact: 0.4, tip: 'Locks deposit amounts before bank carrier takes custody.' }
        ]
      }
    ]
  },
  // 23. Accounts Receivable
  {
    id: 23,
    name: 'Accounts Receivable',
    domain: 'finance-compliance',
    layers: {
      flow: 'Credit Approval → Invoice Issue → Payment Term Tracking → Collection Alerts → Receipt Processing → Aging Audits',
      controls: 'System credit limits, automated payment alerts, manager-approved collection overrides',
      risks: ['Bad debt losses', 'Delayed payments blocking cash flow', 'Unapplied customer credits'],
      kpis: ['Days Sales Outstanding (DSO)', 'Bad Debt Ratio %', 'Collection SLA Compliance %'],
      insights: ['Receivable Aging Heatmap', 'Client Credit Utilization Score', 'Collections Efficiency Score']
    },
    stages: [
      {
        number: 1,
        title: 'Credit Controls',
        controlArea: 'Credit limit system checks',
        checklistItems: [
          { id: 'g-23-1-1', text: 'Confirm ERP blocks credit invoices to clients exceeding credit limits', leakageImpact: 0.3, tip: 'Stops showroom consultants from authorizing risky debtor sales.' }
        ]
      },
      {
        number: 2,
        title: 'Collection Triggers',
        controlArea: 'Payment reminders rules configuration',
        checklistItems: [
          { id: 'g-23-2-1', text: 'Verify automated WhatsApp payment alerts trigger on invoice due dates', leakageImpact: 0.2, tip: 'Ensures immediate outreach to overdue clients.' }
        ]
      },
      {
        number: 3,
        title: 'Aging Reconciliation',
        controlArea: 'Aging audit reviews',
        checklistItems: [
          { id: 'g-23-3-1', text: 'Ensure client ledgers are reconciled weekly against bank deposits', leakageImpact: 0.2, tip: 'Matches cash receipts to invoice accounts.' }
        ]
      }
    ]
  },
  // 24. Accounts Payable
  {
    id: 24,
    name: 'Accounts Payable',
    domain: 'finance-compliance',
    layers: {
      flow: 'Invoice Receipt → Three-Way Match → Pay Cycle Allocation → Approval Sign → Disbursement',
      controls: 'PO-GRN matching rules, pay date controls, supplier tax filing verification',
      risks: ['Duplicate invoice payments', 'Incorrect supplier rates', 'Lost input tax credit on supplier default'],
      kpis: ['AP Cycle Time (days)', 'Lost Discount Opportunities %', 'Payable Match Accuracy Rate %'],
      insights: ['Vendor Payment Aging Matrix', 'Early Settlement Margins Saved', 'Tax Liability Exposure']
    },
    stages: [
      {
        number: 1,
        title: 'Invoice Matching Check',
        controlArea: 'Enforcing three-way match controls',
        checklistItems: [
          { id: 'g-24-1-1', text: 'Audit payment records to block invoices not matching PO/GRN records', leakageImpact: 0.4, tip: 'Stops duplicate or padded supplier billing.' }
        ]
      },
      {
        number: 2,
        title: 'Tax Compliance Verification',
        controlArea: 'Supplier GSTIN filing checks',
        checklistItems: [
          { id: 'g-24-2-1', text: 'Confirm supplier GST returns are verified before payment release', leakageImpact: 0.4, tip: 'Protects input tax credit claims from supplier defaults.' }
        ]
      },
      {
        number: 3,
        title: 'Payment Sign-off',
        controlArea: 'Dual signatory check rules',
        checklistItems: [
          { id: 'g-24-3-1', text: 'Verify dual signatory validation is required for payments exceeding threshold', leakageImpact: 0.3, tip: 'Enforces internal corporate control bounds.' }
        ]
      }
    ]
  },
  // 25. Financial Closing
  {
    id: 25,
    name: 'Financial Closing',
    domain: 'finance-compliance',
    layers: {
      flow: 'Monthly Ledger Check → Accrual Logging → Inventory Valuation → Discrepancy Auditing → Report Generation',
      controls: 'Automatic stock valuation engines, system closing locks, independent audit sign-offs',
      risks: ['Incorrect asset valuation', 'Unrecorded ledger liabilities', 'Delayed reporting cycles'],
      kpis: ['Time to Close (days)', 'Closing Discrepancies count', 'Audit Adjustments Value'],
      insights: ['Showroom Profitability Scorecard', 'Inventory Value Trend Matrix', 'Operating Cost Ratios']
    },
    stages: [
      {
        number: 1,
        title: 'Closing Lockdowns',
        controlArea: 'System transactional closing rules',
        checklistItems: [
          { id: 'g-25-1-1', text: 'Lock ledger transactions for the closing month within 5 days post-close', leakageImpact: 0.3, tip: 'Prevents back-dated ledger adjustments that distort reports.' }
        ]
      },
      {
        number: 2,
        title: 'Stock Valuation Match',
        controlArea: 'Gold rate inventory valuation rules',
        checklistItems: [
          { id: 'g-25-2-1', text: 'Ensure inventory balances are valued using the closing gold index rate', leakageImpact: 0.4, tip: 'Guarantees accurate balance sheet reporting.' }
        ]
      },
      {
        number: 3,
        title: 'Accrual Auditing',
        controlArea: 'Expense matching checks',
        checklistItems: [
          { id: 'g-25-3-1', text: 'Confirm all accrual estimates are signed off by the chief controller', leakageImpact: 0.2, tip: 'Locks operational liabilities.' }
        ]
      }
    ]
  },
  // 26. GST & Regulatory Compliance
  {
    id: 26,
    name: 'GST & Regulatory Compliance',
    domain: 'finance-compliance',
    layers: {
      flow: 'Transaction billing → GSTR-1 preparation → GSTR-2B reconciliations → Tax filing → Audit log lock',
      controls: 'System GST tax code assignments, monthly GSTR-2B matches, statutory audit logs',
      risks: ['GST filing penalties', 'Lost Input Tax Credit', 'Failing statutory HUID compliance audits'],
      kpis: ['GST Reconcile Rate %', 'Filing SLA Compliance %', 'Statutory Exception Rate %'],
      insights: ['Tax Compliance Rating', 'Input Credit Recovery Score', 'Regulatory Risk Map']
    },
    stages: [
      {
        number: 1,
        title: 'GST Code Locks',
        controlArea: 'Standardizing transaction tax calculations',
        checklistItems: [
          { id: 'g-26-1-1', text: 'Ensure tax calculations are auto-mapped based on store region and HSNSAC codes', leakageImpact: 0.4, tip: 'Stops incorrect tax application on invoices.' }
        ]
      },
      {
        number: 2,
        title: 'GSTR-2B Match Check',
        controlArea: 'Reconciliation of tax claim books',
        checklistItems: [
          { id: 'g-26-2-1', text: 'Verify purchase logs are matched monthly against supplier GSTR-2B filings', leakageImpact: 0.4, tip: 'Stops unclaimed Input Tax Credit leaks.' }
        ]
      },
      {
        number: 3,
        title: 'HUID Audit Logs',
        controlArea: 'BIS compliance checklist verification',
        checklistItems: [
          { id: 'g-26-3-1', text: 'Audit active showroom items to mandate valid BIS HUID registration status', leakageImpact: 0.3, tip: 'Avoids heavy statutory penalties for unregistered items.' }
        ]
      }
    ]
  },
  // 27. Approval Matrix Governance
  {
    id: 27,
    name: 'Approval Matrix Governance',
    domain: 'finance-compliance',
    layers: {
      flow: 'User Action Request → System Check of role limits → Override notification → Approval execution → Audit log lock',
      controls: 'Strict system role permissions, manager OTP override triggers, transaction lock thresholds',
      risks: ['Unauthorized price overrides', 'Exceeding budget limits', 'Ghost inventory overrides'],
      kpis: ['Override Exception Rate %', 'Audit Log Adherence %', 'Approval Delay time (mins)'],
      insights: ['Manager Override Hotspots', 'Role Permission Violations Map', 'Budget Override Volumes']
    },
    stages: [
      {
        number: 1,
        title: 'Role Limit Assignment',
        controlArea: 'Access and transactional control checks',
        checklistItems: [
          { id: 'g-27-1-1', text: 'Confirm staff role limits (e.g., maximum discount 2%) are locked in ERP', leakageImpact: 0.3, tip: 'Prevents staff from authorizing margin-eroding sales.' }
        ]
      },
      {
        number: 2,
        title: 'Override Verification',
        controlArea: 'Manager approval controls',
        checklistItems: [
          { id: 'g-27-2-1', text: 'Enforce that transaction exceptions require manager OTP codes', leakageImpact: 0.4, tip: 'Logs accountability for all override instances.' }
        ]
      },
      {
        number: 3,
        title: 'Audit Log Locks',
        controlArea: 'Modifications audit tracking',
        checklistItems: [
          { id: 'g-27-3-1', text: 'Verify override logs are locked and cannot be edited by database administrators', leakageImpact: 0.3, tip: 'Preserves integrity of compliance logs.' }
        ]
      }
    ]
  },

  // HUMAN CAPITAL (28-31)
  // 28. Recruitment & Onboarding
  {
    id: 28,
    name: 'Recruitment & Onboarding',
    domain: 'human-capital',
    layers: {
      flow: 'Profile Application → BG Verify → Security Check → System Role creation → Training → Floor deployment',
      controls: 'Background verification protocols, mandatory security checks, portal training pass check',
      risks: ['Hiring staff with criminal history', 'Unauthorized access on day-1', 'Incorrect role assignment'],
      kpis: ['Onboarding cycle time (days)', 'Background Check Fail Rate %', 'Training Pass Rate %'],
      insights: ['Staff Performance Correlation', 'Hiring Source Quality ratings', 'Attrition by Onboard Cohort']
    },
    stages: [
      {
        number: 1,
        title: 'Background Check Verification',
        controlArea: 'Third-party verification check',
        checklistItems: [
          { id: 'g-28-1-1', text: 'Confirm candidate reference checks are documented prior to contract signing', leakageImpact: 0.2, tip: 'Reduces internal fraud risk by checking past references.' }
        ]
      },
      {
        number: 2,
        title: 'Access Allocation',
        controlArea: 'First-day login controls',
        checklistItems: [
          { id: 'g-28-2-1', text: 'Ensure onboarding login accounts are created only under verified employee codes', leakageImpact: 0.2, tip: 'Prevents creation of untraced access accounts.' }
        ]
      },
      {
        number: 3,
        title: 'Training Compliance',
        controlArea: 'Security and systems tutorial checks',
        checklistItems: [
          { id: 'g-28-3-1', text: 'Verify employee has completed security training before receiving display key cards', leakageImpact: 0.3, tip: 'Enforces standard store security rules.' }
        ]
      }
    ]
  },
  // 29. Employee Performance Management
  {
    id: 29,
    name: 'Employee Performance Management',
    domain: 'human-capital',
    layers: {
      flow: 'KPI Setup → Weekly Floor tracking → Monthly Review → Gap Identification → Coaching → Adjustment',
      controls: 'System target trackers, daily conversion metrics logs, coaching records',
      risks: ['Biased performance reviews', 'Unaddressed conversion decline', 'Disengaged floor staff'],
      kpis: ['Showroom Conversion Rate %', 'Average Ticket size (₹)', 'Loyalty Member Sign-up %'],
      insights: ['Staff Conversion Matrix', 'Coaching Effectiveness Index', 'Retention Lift by Employee']
    },
    stages: [
      {
        number: 1,
        title: 'Target Alignment',
        controlArea: 'Showroom sales target setups',
        checklistItems: [
          { id: 'g-29-1-1', text: 'Verify individual sales targets are loaded into ERP by the 1st of the month', leakageImpact: 0.2, tip: 'Aligns consultant goals with monthly showroom targets.' }
        ]
      },
      {
        number: 2,
        title: 'Floor Analytics Tracking',
        controlArea: 'Daily billing performance audits',
        checklistItems: [
          { id: 'g-29-2-1', text: 'Audit daily consultant conversion logs to flag performance drops', leakageImpact: 0.3, tip: 'Allows store managers to address training gaps immediately.' }
        ]
      },
      {
        number: 3,
        title: 'Coaching Logging',
        controlArea: 'Performance review tracking',
        checklistItems: [
          { id: 'g-29-3-1', text: 'Ensure performance adjustments and coaching records are signed in ERP', leakageImpact: 0.1, tip: 'Maintains records of employee development plans.' }
        ]
      }
    ]
  },
  // 30. Incentive & Commission Management
  {
    id: 30,
    name: 'Incentive & Commission Management',
    domain: 'human-capital',
    layers: {
      flow: 'Billing Complete → Product margin check → Commission calculation → Validation → Pay Ledger entry',
      controls: 'Automatic commission calculators, margin discount caps, independent payment audits',
      risks: ['Paying commissions on returned items', 'Billing staff invoice manipulation', 'Incorrect product tier calculations'],
      kpis: ['Incentive Cost % of Sales', 'Incentive Error Rate %', 'Billing Revision Rate %'],
      insights: ['Sales Incentives ROI', 'Product Margin Lift by Commission tier', 'Incentive Distribution']
    },
    stages: [
      {
        number: 1,
        title: 'Margin Discount Checks',
        controlArea: 'Enforcing incentive limits based on margins',
        checklistItems: [
          { id: 'g-30-1-1', text: 'Block commissions on bills where discount rate exceeds maximum parameters', leakageImpact: 0.3, tip: 'Stops staff from offering heavy discounts to claim volume incentives.' }
        ]
      },
      {
        number: 2,
        title: 'Return Reversals Auditing',
        controlArea: 'Incentive recovery rules configuration',
        checklistItems: [
          { id: 'g-30-2-1', text: 'Enforce that commission payouts are reversed automatically on invoice returns', leakageImpact: 0.4, tip: 'Stops staff from inflating sales volumes via fake return-loop bills.' }
        ]
      },
      {
        number: 3,
        title: 'Payment Reconciliation',
        controlArea: 'Incentive register check audits',
        checklistItems: [
          { id: 'g-30-3-1', text: 'Verify final monthly commission sheets are cross-checked against bank payment accounts', leakageImpact: 0.3, tip: 'Prevents payout duplications.' }
        ]
      }
    ]
  },
  // 31. Attendance & Payroll Controls
  {
    id: 31,
    name: 'Attendance & Payroll Controls',
    domain: 'human-capital',
    layers: {
      flow: 'Biometric Login → Shift check → Overtime approval → Payroll validation → Bank transfer → Pay Slip issue',
      controls: 'Biometric scanners, OT approval limits, dual payroll verifications',
      risks: ['Ghost employee payouts', 'Buddy punching attendance thefts', 'Overtime billing padding'],
      kpis: ['Payroll Error Rate %', 'Overtime Cost % of Base', 'Timecard Exception Rate %'],
      insights: ['Staff Cost to Revenue ratio', 'Overtime Utilization Heatmap', 'Shift Attendance ratings']
    },
    stages: [
      {
        number: 1,
        title: 'Attendance Authentication',
        controlArea: 'Biometric sensor controls',
        checklistItems: [
          { id: 'g-31-1-1', text: 'Enforce biometric (fingerprint/facial) verification for showroom shift logins', leakageImpact: 0.3, tip: 'Eliminates buddy punching and timecard theft.' }
        ]
      },
      {
        number: 2,
        title: 'Overtime Approvals',
        controlArea: 'OT budget limit checks',
        checklistItems: [
          { id: 'g-31-2-1', text: 'Verify extra-shift overtime requires regional manager approvals in ERP', leakageImpact: 0.3, tip: 'Controls floor staffing costs.' }
        ]
      },
      {
        number: 3,
        title: 'Payroll Reconciliation',
        controlArea: 'Bank roster matches checks',
        checklistItems: [
          { id: 'g-31-3-1', text: 'Confirm payroll disbursement files match employee master bank registries', leakageImpact: 0.3, tip: 'Prevents cash routing to unverified bank details.' }
        ]
      }
    ]
  },

  // EXECUTIVE CONTROL (32-36)
  // 32. Retail KPI Engine
  {
    id: 32,
    name: 'Retail KPI Engine',
    domain: 'executive-control',
    layers: {
      flow: 'Data Collection → Telemetry processing → Metric calculation → Scorecard generation → Exec review',
      controls: 'Automated telemetry database feeds, system metric calculations, dashboard display controls',
      risks: ['Stale dashboard data', 'Manual metric calculation errors', 'Key business performance blindness'],
      kpis: ['Dashboard Sync Frequency (mins)', 'Data Discrepancy Rate %', 'Executive Usage Rate %'],
      insights: ['Causation Tracking Metrics', 'Showroom Performance rankings', 'Business Margin Analysis']
    },
    stages: [
      {
        number: 1,
        title: 'Data Feed Verification',
        controlArea: 'Telemetry database sync controls',
        checklistItems: [
          { id: 'g-32-1-1', text: 'Verify live database sync is active with less than 15 minutes lag', leakageImpact: 0.3, tip: 'Ensures dashboards display real-time operational metrics.' }
        ]
      },
      {
        number: 2,
        title: 'Metric Calculation Audit',
        controlArea: 'Verification of formula scripts',
        checklistItems: [
          { id: 'g-32-2-1', text: 'Audit calculation engines to verify margins use net gold costs excluding tax', leakageImpact: 0.4, tip: 'Prevents distortion of profitability metrics.' }
        ]
      },
      {
        number: 3,
        title: 'Security Access Control',
        controlArea: 'Dashboard access credentials check',
        checklistItems: [
          { id: 'g-32-3-1', text: 'Confirm dashboard access is restricted using Client Vault passcode credentials', leakageImpact: 0.4, tip: 'Protects proprietary corporate operational data.' }
        ]
      }
    ]
  },
  // 33. Retail Operating System
  {
    id: 33,
    name: 'Retail Operating System',
    domain: 'executive-control',
    layers: {
      flow: 'Policy definition → Workflow configuration → ERP integration → Staff training → System audits',
      controls: 'Target Operating Model blueprints, workflow system locks, role privilege matrix',
      risks: ['System workarounds by staff', 'Unmapped data silos', 'Bypassing process control gates'],
      kpis: ['Process Compliance Score %', 'Active Workarounds count', 'System Usage Rate %'],
      insights: ['Process Performance Hotspots', 'Operational Risk Heatmap', 'System ROI Matrix']
    },
    stages: [
      {
        number: 1,
        title: 'Process Mapping',
        controlArea: 'Defining standard operating procedures',
        checklistItems: [
          { id: 'g-33-1-1', text: 'Confirm SOP flowcharts are documented for all 36 core showroom workflows', leakageImpact: 0.2, tip: 'Establishes standardized training guidelines.' }
        ]
      },
      {
        number: 2,
        title: 'ERP Integration Audit',
        controlArea: 'Process gate enforcement controls',
        checklistItems: [
          { id: 'g-33-2-1', text: 'Verify key process steps (e.g., GRN to Payment) require system validation', leakageImpact: 0.4, tip: 'Prevents staff from skipping audit gates.' }
        ]
      },
      {
        number: 3,
        title: 'Compliance Reviews',
        controlArea: 'Operational review check schedules',
        checklistItems: [
          { id: 'g-33-3-1', text: 'Schedule quarterly operational compliance reviews to test systems validity', leakageImpact: 0.3, tip: 'Maintains system alignment with evolving business requirements.' }
        ]
      }
    ]
  },
  // 34. Executive Decision Intelligence
  {
    id: 34,
    name: 'Executive Decision Intelligence',
    domain: 'executive-control',
    layers: {
      flow: 'Boardroom agenda mapping → Scenario simulation → Risk evaluation → Capital allocation signoff → Monitor',
      controls: 'Scenario simulation models, capital allocation approval matrix, boardroom decision logs',
      risks: ['Gut-based capital decisions', 'Underestimating inventory risk', 'Incorrect cash flow projections'],
      kpis: ['Scenario Simulation Accuracy %', 'Board Decision Implementation rate', 'Capital ROI Lift %'],
      insights: ['EBITDA Impact projections', 'Multi-dimensional Risk Map', 'Boardroom Performance Scorecard']
    },
    stages: [
      {
        number: 1,
        title: 'Boardroom Agenda prep',
        controlArea: 'Documenting decision-support requests',
        checklistItems: [
          { id: 'g-34-1-1', text: 'Verify executive reports include scenario simulations for capital allocation options', leakageImpact: 0.4, tip: 'Helps directors make informed decisions based on projected outcomes.' }
        ]
      },
      {
        number: 2,
        title: 'Scenario Simulation validation',
        controlArea: 'Verifying projection model scripts',
        checklistItems: [
          { id: 'g-34-2-1', text: 'Audit mathematical models for cash projections against history values', leakageImpact: 0.4, tip: 'Guarantees reliability of financial models.' }
        ]
      },
      {
        number: 3,
        title: 'Approval Logs',
        controlArea: 'Capital allocation decision sign-off registers',
        checklistItems: [
          { id: 'g-34-3-1', text: 'Confirm all capital project releases (>₹10Cr) are logged in the ERP dashboard', leakageImpact: 0.3, tip: 'Maintains accountability for large capital expenditures.' }
        ]
      }
    ]
  },
  // 35. Risk & Fraud Management
  {
    id: 35,
    name: 'Risk & Fraud Management',
    domain: 'executive-control',
    layers: {
      flow: 'Risk Identification → Trigger setup → Real-time alert dispatch → Investigation → Loss recovery → Protocol update',
      controls: 'Automated anomaly scanners, real-time security alerts, independent fraud audit checks',
      risks: ['Undetected internal theft', 'Fake diamond substitution schemes', 'Cash transaction money laundering'],
      kpis: ['Fraud Alerts Dispatched count', 'Avg Investigation Time (hours)', 'Loss Recovery Rate %'],
      insights: ['Fraud Exposure index by store', 'Loss Recovery Effectiveness Score', 'Security Threat map']
    },
    stages: [
      {
        number: 1,
        title: 'Anomaly Scanners Setup',
        controlArea: 'Real-time transaction scanner rules',
        checklistItems: [
          { id: 'g-35-1-1', text: 'Enable system alerts for repeat manual barcode bypasses in showroom till registers', leakageImpact: 0.5, tip: 'Flags potential cashier gold substitution scams.' }
        ]
      },
      {
        number: 2,
        title: 'Assay Audit Logs',
        controlArea: 'Karatometer assay scan registry check',
        checklistItems: [
          { id: 'g-35-2-1', text: 'Verify Karatometer logs are cross-checked daily against buyback inventory balances', leakageImpact: 0.4, tip: 'Detects acceptance of counterfeit or gold-plated jewellery.' }
        ]
      },
      {
        number: 3,
        title: 'Loss Investigations',
        controlArea: 'Independent audit team dispatch',
        checklistItems: [
          { id: 'g-35-3-1', text: 'Enforce independent audits on stores with >0.5% unexplained weight discrepancies', leakageImpact: 0.4, tip: 'Triggers prompt action on high-loss showrooms.' }
        ]
      }
    ]
  },
  // 36. Internal Audit & Compliance
  {
    id: 36,
    name: 'Internal Audit & Compliance',
    domain: 'executive-control',
    layers: {
      flow: 'Audit planning → Store audit field visits → Control testing → Exception logging → Remediation tracking → Close',
      controls: 'Independent auditor rosters, standardized control testing sheets, remediation follow-up trackers',
      risks: ['Auditor bribe collusion', 'Incomplete compliance testing', 'Unresolved operational audit exceptions'],
      kpis: ['Audit Plan Adherence %', 'Remediation Closure Rate %', 'Compliance Testing Scope %'],
      insights: ['Compliance Risk Score by region', 'Audit Exception Repeat Rate Matrix', 'Control Effectiveness Index']
    },
    stages: [
      {
        number: 1,
        title: 'Audit Planning',
        controlArea: 'Audit scope definitions',
        checklistItems: [
          { id: 'g-36-1-1', text: 'Ensure store audit plans cover all 36 processes in the governance library', leakageImpact: 0.3, tip: 'Guarantees comprehensive coverage of operational risk domains.' }
        ]
      },
      {
        number: 2,
        title: 'Exception Logging',
        controlArea: 'Standardized exception reporting rules',
        checklistItems: [
          { id: 'g-36-2-1', text: 'Log compliance exceptions in the ERP immediately upon detection', leakageImpact: 0.4, tip: 'Prevents staff from burying or delaying audit results.' }
        ]
      },
      {
        number: 3,
        title: 'Remediation tracking',
        controlArea: 'Follow-up timeline validations',
        checklistItems: [
          { id: 'g-36-3-1', text: 'Confirm system blocks audit close status until all high-risk gaps are resolved', leakageImpact: 0.4, tip: 'Ensures store managers implement recommended remediations.' }
        ]
      }
    ]
  }
];
